server:
  port: 8080

spring:
  application:
    name: queryDslExam

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: '1234'

  h2:
    console:
      enabled: false

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      platform: postgres